server { 
    server_name y2factory-dao.com www.y2factory-dao.com; 
    client_max_body_size 10M; 
    
    # NGINX DIRECTLY SERVES UPLOADED FILES Bypass Next.js
    location /uploads/ {
        alias /var/www/y2factory-dao/public/uploads/;
        access_log off;
        expires max;
    }

    location / { 
        proxy_pass http://127.0.0.1:3000; 
        proxy_http_version 1.1; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
    } 
    
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/y2factory-dao.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/y2factory-dao.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.y2factory-dao.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = y2factory-dao.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80; 
    server_name y2factory-dao.com www.y2factory-dao.com;
    return 404; # managed by Certbot
}
